---
permalink: /:year/:month/:day/:title
markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'smart']
sponsors:
  banners:
    -
      name: Ken Berger
      link: 'http://www.bergerlawsc.com/'
      img: /img/Sponsors/berger-small.jpg
  primary:
    -
      name: Gentle Dentistry
      link: 'http://www.peacefuldentistry.com'
      img: /img/Sponsors/GDOG1.jpg
    -
      name: Caughmans
      link: 'http://www.caughmanmeats.com'
      img: /img/Sponsors/Meat.jpg
    -
      name: Raymond James Financial
      link: 'http://www.christopherbbenson.com/'
      img: /img/Sponsors/raymondjames.jpg
    -
      name: Seasons by the Lake
      link: 'http://www.clemson.edu/centers-institutes/madren/dining.html'
      img: /img/Sponsors/Seasons1.jpg
    -
      name: James F. Martin Inn
      link: 'http://www.clemson.edu/centers-institutes/madren/inn'
      img: /img/Sponsors/James_F_Martin1.jpg
    -
      name: "Frank's Car Wash"
      link: 'http://www.frankscarwash.com/'
      img: /img/Sponsors/franks.jpg
    -
      name: "Cellular Source"
      link: 'http://www.cellularsourcestore.com/'
      img: /img/Sponsors/cellsource.jpg
    -
      name: "Meridian Printing"
      link: 'http://mbspromo.com/'
      img: /img/Sponsors/meridian.jpg
  secondary:
    -
      name: Edisto Outdoors
      link: 'http://www.edistooutdoors.com'
      img: /img/Sponsors/EO1.jpg
    -
      name: Lake Murray Times
      link: 'http://lakemurraytimes.com/'
      img: /img/Sponsors/LakeMurrayTimes.jpg
    -
      name: Econobug
      link: 'http://www.econobugpestcontrol.com/'
      img: /img/Sponsors/econobug.jpg
    -
      name: Palmetto Ground Services
      link: 'http://www.palmettogroundsservices.com/'
      img: /img/Sponsors/pgroundservices.jpg
