---
permalink: /:year/:month/:day/:title
markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'smart']
sponsors:
  banners:
  primary:
    -
      name: Gentle Dentistry
      link: 'http://www.peacefuldentistry.com'
      img: /img/Sponsors/GDOG1.jpg
    -
      name: Caughmans
      link: 'http://www.caughmanmeats.com'
      img: /img/Sponsors/Meat.jpg
    -
      name: Raymond James Financial
      link: 'http://www.christopherbbenson.com/'
      img: /img/Sponsors/raymondjames.jpg
    -
      name: 'Woodward, Cothran & Herndon'
      link: 'http://www.wchlaw.com/'
      img: /img/Sponsors/wchlaw.jpg
    
  secondary:
    -
      name: Edisto Outdoors
      link: 'http://www.edistooutdoors.com'
      img: /img/Sponsors/EO1.jpg
    -
      name: Palmetto Ground Services
      link: 'http://www.palmettogroundsservices.com/'
      img: /img/Sponsors/pgroundservices.jpg
    -
      name: "Cellular Source"
      link: 'http://www.cellularsourcestore.com/'
      img: /img/Sponsors/cellsource.jpg
    -
      name: "Meridian Printing"
      link: 'http://mbspromo.com/'
      img: /img/Sponsors/meridian.jpg
