---
permalink: /:year/:month/:day/:title
sponsors:
  banners:
  primary:
    -
      name: Mosquito Joe
      link: 'http://lakemurray.mosquitojoe.com/'
      img: /img/MJoe.jpg
    -
      name: Caughmans
      link: 'http://www.caughmanmeats.com'
      img: /img/download2.png
    -
      name: Caribbean Resort and Villas
      link: 'http://www.caribbeanresort.com/'
      img: /img/Caribbean.jpg
    -
      name: 'SakiTumi'
      link: 'http://sakifresh.com/'
      img: '/img/Sponsors/saki.jpg'
    -
      name: 'Tiger Sports Shop'
      link: 'http://www.tigersports.com/'
      img: '/img/TigerSports.png'
    -
      name: 'Carolina Conditions'
      link: 'http://www.carolinaconditions.com/'
      img: '/img/carolinaconditions.png'
    -
      name: 'CFIM'
      link: 'http://crossfitironmarys.com/'
      img: '/img/CFIM.png'
    -
      name: 'Hobbs Group'
      link: 'http://www.hobbscpa.com/'
      img: '/img/Sponsors/hobbs.jpg'
  
  secondary:
    -
      name: The Lost Cajun
      link: 'http://www.thelostcajun.com/locations/lexington-south-carolina'
      img: /img/lostcajun.jpg
    -
      name: Edisto Outdoors
      link: 'http://www.edistooutdoors.com'
      img: /img/Sponsors/EO1.jpg
    -
      name: Meridian Printing
      link: 'http://mbspromo.com/'
      img: /img/Sponsors/meridian.jpg
    -
      name: Lexington Medical Center
      link: 'http://www.lexmed.com/'
      img: /img/Sponsors/lexmed.jpg
    -
      name: 'Fairey Chevrolet-Cadillac'
      link: 'http://www.faireychevrolet.com/'
      img: /img/FCC.png
    -
      name: 'Old South Lanscaping'
      link: 'http://www.oldsouthsc.com/'
      img: /img/OSouth.jpg
    -
      name: HealthSource Chiropractic
      link: 'https://healthsourcechiro.com/'
      img: /img/Sponsors/healthsource.jpg
    -
      name: South Lake Drug
      link: 'http://southlakerx.com/'
      img: /img/Southlakelogo.png
