---
permalink: /:year/:month/:day/:title
markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'smart', 'hard_wrap']
sponsors:
  primary:
    -
      name: Cross Creek Timber
      link: 'http://www.crosscreektimber.com'
      img: /img/Sponsors/Cross_Creek1.jpg
    -
      name: Peaceful Dentistry
      link: 'http://www.peacefuldentistry.com'
      img: /img/Sponsors/GDOG1.jpg
    -
      name: CMH 
      link: 'http://www.cmhservices.net/'
      img: /img/Sponsors/CMH1.jpg    
    -
      name: Lake Murray Times
      link: 'http://lakemurraytimes.com/'
      img: /img/Sponsors/LakeMurrayTimes.jpg 
  secondary:
    -
      name: Edisto Outdoors
      link: 'http://www.edistooutdoors.com'
      img: /img/Sponsors/EO1.jpg
    -
      name: Caughman
      link: 'http://www.caughmanmeats.com'
      img: /img/Sponsors/Meat.jpg
    -
      name: Cross Creek Realty
      link: 'http://www.crosscreekrealtyllc.com'
      img: /img/Sponsors/CCRealty.jpg
    -
      name: SCFBINS
      link: 'http://scfbins.com/agents/blake-austin/'
      img: /img/Sponsors/FB1.jpg