---
permalink: /:year/:month/:day/:title
markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'smart']
sponsors:
  banners:
    -
      name: Ken Berger
      link: 'http://www.bergerlawsc.com/'
      img: /img/Sponsors/berger.jpg
    -
      name: Tiger Paw Traditions
      link: 'http://www.tigerpawtraditions.com/default.aspx?ad_id=clsptk'
      img: /img/Sponsors/tpt-banner.jpg
  primary:
    -
      name: Peaceful Dentistry
      link: 'http://www.peacefuldentistry.com'
      img: /img/Sponsors/GDOG1.jpg
    -
      name: CMH
      link: 'http://www.cmhservices.net/'
      img: /img/Sponsors/CMH1.jpg
    -
      name: Caughmans
      link: 'http://www.caughmanmeats.com'
      img: /img/Sponsors/Meat.jpg
    -
      name: Raymond James Financial
      link: 'http://www.christopherbbenson.com/'
      img: /img/Sponsors/raymondjames.jpg
    -
      name: Seasons by the Lake
      link: 'http://www.clemson.edu/centers-institutes/madren/dining.html'
      img: /img/Sponsors/Seasons1.jpg
    -
      name: James F. Martin Inn
      link: 'http://www.clemson.edu/centers-institutes/madren/inn'
      img: /img/Sponsors/James_F_Martin1.jpg
    -
      name: Lexington Medical Center
      link: 'http://www.lexmed.com/'
      img: /img/Sponsors/lexmed.jpg
    -
      name: Tiger Paw Traditions
      link: 'http://www.tigerpawtraditions.com/default.aspx?ad_id=clsptk'
      img: /img/Sponsors/tpt.jpg
  secondary:
    -
      name: Chapin Pharmacy
      link: 'http://www.chapinpharmacy.com/'
      img: /img/Sponsors/chapinmed.jpg
    -
      name: Edisto Outdoors
      link: 'http://www.edistooutdoors.com'
      img: /img/Sponsors/EO1.jpg
    -
      name: Lake Murray Times
      link: 'http://lakemurraytimes.com/'
      img: /img/Sponsors/LakeMurrayTimes.jpg
    -
      name: SCFBINS
      link: 'http://scfbins.com/agents/blake-austin/'
      img: /img/Sponsors/FB1.jpg
